# name: CD
# on: 
#   - push: 
#     - branches: 
#       - master
#       - develop

#   - pull_request:
#     - branches:
#       - master
#       - develop

# jobs:
#   deploy:
#     needs: push-image
#   steps:
#     ...
